# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f5c470d4e0eb95aaa0ad4ea7b79cdbb1dab638a3f51fe3b024a8bdb309e24c0b9a500f65519660e9076c128797fb796e727d3a23288b3c2ea87d271e5a17f6c

test:
  secret_key_base: d749fd13ca9ea03331820a5cc3ed3ad6887273f4585243977ba7599cfbe18f874def5007309087fdbed898e23ab40ac1489771c12ed6a3db22c7a47c64781168

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
